# -*- coding: utf-8 -*-
"""Lab4_task7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aotVnqKR8ljpZ2AZ5bHWwpJWeAXncmmW
"""

import numpy as np
import matplotlib.pyplot as plt

X = np.array([0.3, 1.0, 1.5, 2.2, 3.6, 4.5])
Y = np.array([5, 10, 13, 16, 17, 18])
n = len(X)

beta1 = (n * np.sum(X*Y) - np.sum(X) * np.sum(Y)) / (n * np.sum(X**2) - (np.sum(X))**2)
beta0 = np.mean(Y) - beta1 * np.mean(X)

print(f"β0 = {beta0:.2f}")
print(f"β1 = {beta1:.2f}")
print(f"Рівняння прямої: y = {beta0:.2f} + {beta1:.2f}x")

Y_pred = beta0 + beta1 * X
S = np.sum((Y - Y_pred)**2)
print(f"S({beta0:.2f}; {beta1:.2f}) = {S:.6f}")

plt.scatter(X, Y, color='blue', label='Експериментальні точки')
plt.plot(X, Y_pred, color='red', label='Апроксимація (МНК)')
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Метод найменших квадратів')
plt.legend()
plt.grid(True)
plt.show()