# -*- coding: utf-8 -*-
"""Lab4_task6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7vr1g7Jf2pNx44wdNCgsBPZ-URQSqS3
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures

def plot_learning_curves(model, X, y):
    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)
    train_errors, val_errors = [], []

    for m in range(1, len(X_train)):
        model.fit(X_train[:m], y_train[:m])
        y_train_predict = model.predict(X_train[:m])
        y_val_predict = model.predict(X_val)
        train_errors.append(mean_squared_error(y_train_predict, y_train[:m]))
        val_errors.append(mean_squared_error(y_val_predict, y_val))

    plt.plot(np.sqrt(train_errors), "r-+", linewidth=2, label="Навчальний набір (помилка)")
    plt.plot(np.sqrt(val_errors), "b-", linewidth=3, label="Перевірочний набір (помилка)")
    plt.legend()
    plt.xlabel("Кількість навчальних даних")
    plt.ylabel("RMSE (середньоквадратична помилка)")
    plt.grid(True)

def generate_data(m):
    np.random.seed(42)
    X = np.linspace(-3, 3, m).reshape(-1, 1)
    y = 3 + np.sin(X) + np.random.uniform(-0.5, 0.5, (m, 1))

    return X, y

m = 100
X, y = generate_data(m)

lin_reg = LinearRegression()
plt.figure(figsize=(10, 5))
plt.title("Криві навчання: Лінійна регресія")
plot_learning_curves(lin_reg, X, y)
plt.show()

polynomial_regression_10 = Pipeline([
    ("poly_features", PolynomialFeatures(degree=10, include_bias=False)),
    ("lin_reg", LinearRegression()),
])
plt.figure(figsize=(10, 5))
plt.title("Криві навчання: Поліном 10-го ступеня")
plot_learning_curves(polynomial_regression_10, X, y)
plt.show()

polynomial_regression_2 = Pipeline([
    ("poly_features", PolynomialFeatures(degree=2, include_bias=False)),
    ("lin_reg", LinearRegression()),
])
plt.figure(figsize=(10, 5))
plt.title("Криві навчання: Поліном 2-го ступеня")
plot_learning_curves(polynomial_regression_2, X, y)
plt.show()