# -*- coding: utf-8 -*-
"""LR6_task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kFvTrxk6R5Lb9AW2EC3s3UDHYfzFjlpa
"""

import pandas as pd

df = pd.read_csv('play_tennis.csv')

cnt = df['Day'].count()

p_yes = len(df[df['Play'] == 'Yes']) / cnt
p_no = len(df[df['Play'] == 'No']) / cnt

print(f"P(Yes): {p_yes}")
print(f"P(No): {p_no}")

P_Sunny_Yes = len(df[(df['Outlook'] == 'Sunny') & (df['Play'] == 'Yes')]) / len(df[df['Play'] == 'Yes'])
P_Sunny_No = len(df[(df['Outlook'] == 'Sunny') & (df['Play'] == 'No')]) / len(df[df['Play'] == 'No'])

P_Normal_Yes = len(df[(df['Humidity'] == 'Normal') & (df['Play'] == 'Yes')]) / len(df[df['Play'] == 'Yes'])
P_Normal_No = len(df[(df['Humidity'] == 'Normal') & (df['Play'] == 'No')]) / len(df[df['Play'] == 'No'])

P_Strong_Yes = len(df[(df['Wind'] == 'Strong') & (df['Play'] == 'Yes')]) / len(df[df['Play'] == 'Yes'])
P_Strong_No = len(df[(df['Wind'] == 'Strong') & (df['Play'] == 'No')]) / len(df[df['Play'] == 'No'])

P_yes_final = P_Sunny_Yes * P_Normal_Yes * P_Strong_Yes * p_yes
P_no_final = P_Sunny_No * P_Normal_No * P_Strong_No * p_no

print(f"\nЙмовірність гри (Yes): {P_yes_final:.4f}")
print(f"Ймовірність відсутності гри (No): {P_no_final:.4f}")

if P_yes_final > P_no_final:
    total_score = P_yes_final + P_no_final

real_percent_yes = P_yes_final / total_score
real_percent_no = P_no_final / total_score

print(f"\n--- Нормалізовані ймовірності ---")
print(f"Ймовірність 'Yes': {real_percent_yes:.4f} (або {real_percent_yes*100:.1f}%)")
print(f"Ймовірність 'No':  {real_percent_no:.4f} (або {real_percent_no*100:.1f}%)")

if real_percent_yes > real_percent_no:
    print("Результат: Матч відбудеться")
else:
    print("Результат: Матч не відбудеться")